# database:
#   name: "dev_database"
#   schema: "dev_schema"
#   table_prefix: "dev_"

gcp:
  project_id: "de-project-444809"
  bucket_name: "de-project-yokin-bucket-dev"
  # dataset: "dev_dataset"
  location: "asia-east1"

dbt:
  target: "dev"
  profiles_dir: "/opt/dbt"


local_postgres:
  host:"dev-postgres-1"

alerts:
  email_on_failure: false
  email_on_retry: false